vpc_name      = "amirk-tf-vpc-portfolio"
subnet_a_name = "amirk-tf-subnet-1a"
subnet_b_name = "amirk-tf-subnet-1b"
cluster_name   = "amirk-tf-eks-portfolio"
node_group_name= "amirk-tf-eks-node-group-portfolio"