
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:AmirKatorza/develeap-portfolio-poster-downloader-gitops.git
    targetRevision: HEAD
    path: poster-downloader
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true