
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@gitlab.com:develeap191/argocd-nana-tutorial.git
    targetRevision: HEAD
    path: poster-downloader
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true